'use client';

import { useState } from 'react';
import Image from 'next/image';
import type { Plot } from '@/lib/definitions';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertTriangle, BrainCircuit, Loader2, Sparkles } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';

export default function SitePlanGenerator({ plot }: { plot: Plot }) {
  const [sitePlanUrl, setSitePlanUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const isApiKeyConfigured = process.env.NEXT_PUBLIC_GEMINI_API_KEY_CONFIGURED === 'true';

  const handleGenerate = async () => {
    setError('AI features are temporarily disabled for build stability. They will be re-enabled in a future update.');
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center">
            <BrainCircuit className="h-6 w-6 mr-3 text-primary" />
            AI Site Plan Generator
        </CardTitle>
        <CardDescription>
            Visualize a potential house layout for this plot, generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isLoading && (
            <div className="aspect-video w-full flex flex-col items-center justify-center bg-muted/50 rounded-lg">
                <Loader2 className="h-12 w-12 text-primary animate-spin" />
                <p className="mt-4 text-muted-foreground font-medium">Generating your site plan...</p>
                <p className="text-sm text-muted-foreground">This may take up to 30 seconds.</p>
            </div>
        )}

        {!isLoading && error && (
          <Alert variant="destructive">
            <AlertTriangle className="h-4 w-4" />
            <AlertTitle>Generation Failed</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {!isLoading && sitePlanUrl && (
          <div className="relative aspect-video w-full rounded-lg overflow-hidden border shadow-sm">
            <Image src={sitePlanUrl} alt="AI-generated site plan" fill className="object-contain" />
          </div>
        )}
        
        {!isApiKeyConfigured && (
            <Alert>
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle>Feature Disabled</AlertTitle>
                <AlertDescription>
                    The AI Site Plan Generator requires a Gemini API key to be configured by the developer.
                </AlertDescription>
            </Alert>
        )}

      </CardContent>
      <CardContent>
         <Button onClick={handleGenerate} disabled={isLoading || !isApiKeyConfigured} className="w-full">
          {isLoading ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <Sparkles className="mr-2 h-4 w-4" />
          )}
          {sitePlanUrl ? 'Regenerate Site Plan' : 'Generate Site Plan'}
        </Button>
      </CardContent>
    </Card>
  );
}
